version: "3.9"

services:
  db:
    image: mysql:5.7
    command: --sql-mode="" --innodb-buffer-pool-size=256M --innodb-log-file-size=64M
    environment:
      MYSQL_DATABASE: bedrock
      MYSQL_USER: bedrock
      MYSQL_PASSWORD: bedrock
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./geronimo_basic.sql:/docker-entrypoint-initdb.d/00_seed.sql:ro
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 2048M
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - php

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "1000"
    command: sh -lc "yarn install && ./node_modules/.bin/gulp dev"
    tty: true
    stdin_open: true

  wpcli:
    image: wordpress:cli-php7.4
    user: "33:33"
    working_dir: /var/www/html
    environment:
      WORDPRESS_CONFIG_EXTRA: ""
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - db

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

volumes:
  db_data:
